# Generated by Django 5.0.6 on 2024-06-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
