# Generated by Django 5.0.6 on 2024-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='stock_oferta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
