# Generated by Django 5.0.6 on 2024-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_oferta_stock_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='numero_producto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
